### ISSUE TITLE
eliminate hardcodes in do_fix_entry

### ISSUE THREAD

**Issue by mark14wu** [OSH-2018/X-yeahtiger#1]
"nm /usr/local/lib/libtfix.so | grep do_fix_entry"
could any help me remove the hardcode @wtx1999 
in python plz

**Comment by weitianxin** [comment]
import lief
libm_tfix=lief.ELF.parse("/usr/local/lib/libtfix.so")
symbol_name=[x.name for x in libm_tfix.symbols]
if "do_fix_entry" in symbol_name:
    tfix=libm_tfix.get_symbol("do_fix_entry")
    print(tfix.value)
else:
    raise NameError("do_fix_entry not found")

**Comment by mark14wu** [comment]
thanks!
